name: CLOC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Code Lines Badge
      uses: Kherrisan/cloc-badge-action@1.0.1