name: Create and publish a package
on:
  push:
    branches: ['master']
jobs:

  run-npm-package:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12  
    - run: npm install
    - run: npm publish
