name: Create and publish a package
on:
  push:
    branches: ['master']
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true

  run-npm-package:
    runs-on: ubuntu-latest
    needs: run-npm-test  
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        run: npm version patch      
      - uses: actions/setup-node@v1
        with:
          node-version: 12  
      - run: npm install
      - run: npm publish